# Generated by Django 3.0.5 on 2020-12-26 22:14

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201225_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='/mnt/c/Users/sra61/OneDrive - UFV/UFV/3/1Cuatri/IS2/proyectoIS2/srcmyfiles/', collection='myfiles'), upload_to='authors'),
        ),
    ]
