# Generated by Django 3.0.5 on 2020-12-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201226_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
