# Generated by Django 3.0.5 on 2020-12-27 21:06

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201226_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='posts/'),
        ),
    ]
