# Generated by Django 3.0.5 on 2020-12-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201227_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
