# Generated by Django 3.0.5 on 2020-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201228_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.CharField(max_length=100),
        ),
    ]
